import React, { useState } from 'react';
import PageFrame, { Field, Panel } from '../components/PageFrame';

export default function Screener() {
  const [marketCap, setMarketCap] = useState('500');
  const [peg, setPeg] = useState('1.5');
  const [roe, setRoe] = useState('15');
  return <PageFrame eyebrow="Pipeline stage 01-03" title="Screener" description="Tune the universe and quality filters before a company enters manual review. Values are editable and ready to connect to the backend pipeline.">
    <div className="grid gap-6 lg:grid-cols-[280px_1fr]"><Panel title="Filter thresholds"><div className="mt-5 space-y-4"><label className="block text-sm font-medium text-slate-700">Market<select className="mt-2 w-full rounded-md border border-slate-300 bg-white px-3 py-2 font-normal"><option>All markets</option><option>US</option><option>India</option></select></label><Field label="Minimum market cap ($M)" value={marketCap} onChange={setMarketCap} /><Field label="Maximum PEG" value={peg} onChange={setPeg} /><Field label="Minimum ROE (%)" value={roe} onChange={setRoe} /><button className="w-full rounded-md bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Apply filters</button></div></Panel><Panel title="Pipeline preview"><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-md bg-sky-50 p-4"><p className="text-2xl font-bold text-sky-800">2,481</p><p className="text-sm text-sky-700">Universe</p></div><div className="rounded-md bg-emerald-50 p-4"><p className="text-2xl font-bold text-emerald-800">284</p><p className="text-sm text-emerald-700">Quality + GARP</p></div><div className="rounded-md bg-violet-50 p-4"><p className="text-2xl font-bold text-violet-800">28</p><p className="text-sm text-violet-700">Manual review</p></div></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[600px] text-sm"><thead className="text-left text-xs uppercase tracking-wider text-slate-500"><tr><th className="py-3">Ticker</th><th>Market</th><th>PEG</th><th>ROE</th><th>Beneish</th><th>Status</th></tr></thead><tbody>{[['AEHR', 'US', '0.85', '18.0%', '-3.14', 'Pass'], ['TCS.NS', 'India', '0.92', '45.0%', '-2.87', 'Pass'], ['DIXON.NS', 'India', '1.18', '28.0%', '-2.08', 'Review']].map((row) => <tr key={row[0]} className="border-t border-slate-100"><td className="py-3 font-semibold">{row[0]}</td>{row.slice(1).map((value, index) => <td key={`${row[0]}-${index}`} className={value === 'Pass' ? 'font-semibold text-emerald-700' : ''}>{value}</td>)}</tr>)}</tbody></table></div></Panel></div>
  </PageFrame>;
}
