import React, { useState } from 'react';
import PageFrame, { Panel } from '../components/PageFrame';

export default function Sentiment() {
  const [fileName, setFileName] = useState('');
  return <PageFrame eyebrow="Filing review" title="Sentiment analysis" description="Upload a 10-K or annual report to inspect MD&A tone, consistency, and red-flag language before manual review.">
    <div className="grid gap-6 lg:grid-cols-[1fr_1fr]"><Panel title="Upload filing"><label className="mt-5 flex min-h-48 cursor-pointer flex-col items-center justify-center rounded-md border-2 border-dashed border-slate-300 bg-slate-50 p-6 text-center hover:border-emerald-500"><input type="file" accept=".pdf,.html,.htm" className="sr-only" onChange={(event) => setFileName(event.target.files?.[0]?.name || '')} /><span className="text-sm font-semibold text-slate-700">Choose a PDF or HTML filing</span><span className="mt-2 text-xs text-slate-500">The MD&A section will be parsed for analysis</span>{fileName && <span className="mt-4 rounded bg-emerald-100 px-2 py-1 text-xs text-emerald-800">{fileName}</span>}</label><button className="mt-4 w-full rounded-md bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Analyze filing</button></Panel><Panel title="Analysis preview"><div className="mt-5 space-y-4"><div className="flex items-center justify-between border-b border-slate-100 pb-4"><span className="text-sm text-slate-500">Sentiment score</span><strong className="text-2xl text-emerald-700">+0.42</strong></div><div className="flex items-center justify-between border-b border-slate-100 pb-4"><span className="text-sm text-slate-500">Year-over-year tone</span><strong className="text-sm text-emerald-700">Improving</strong></div><div className="flex items-center justify-between border-b border-slate-100 pb-4"><span className="text-sm text-slate-500">Topic consistency</span><strong className="text-sm">84%</strong></div><div className="flex items-center justify-between"><span className="text-sm text-slate-500">Red flags</span><strong className="text-sm text-amber-700">2 to review</strong></div></div></Panel></div>
  </PageFrame>;
}
